apiVersion: v1
kind: Secret
metadata:
  name: cap-sec 
  namespace: capstone
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: Y2Fwc3RvbmU=
  MYSQL_PASSWORD: Y2Fwc3RvbmU=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mys-config
  namespace: capstone
data:
  WORDPRESS_DB_HOST: mysql-state-0.mysql-svc.capstone.svc.cluster.local:3306
  WORDPRESS_DB_NAME: capstone