apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    apps: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: postgres
  template:
    metadata:
      labels:
        apps: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_DB
          volumeMounts:
            - name: init 
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true  
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
      volumes:
        - name: init
          configMap:
            name: pg-config  
        - name: pgdata
          persistentVolumeClaim:
            claimName: my-pvc   