apiVersion: v1
kind: Pod
metadata: 
  name: busybox
  labels:
    app: myapp
  namespace: prod
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "echo hello from busybox && sleep 3600"]