apiVersion: v1
kind: Pod
metadata:
  name: stresspod 
  labels:
    app: stress
spec:
  containers: 
    - name: stress
      image: polinux/stress:1.0.4
      command: ["stress"]
      args:
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "250M"
        - "--vm-hang"
        - "1"
      resources:
        requests:
          cpu: "100"
          memory: "128Gi"
        limits:
          cpu: "200"
          memory: "200Gi"